name: pyrtools_docs

channels:
  - conda-forge

dependencies:
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - numpy
  - python
  - pip==9.0.3
  - ipython
  - pip:
    - nbsphinx
    - nbsphinx_link
    - sphinxcontrib-apidoc
